### ISSUE TITLE
Update to 1.15

### ISSUE THREAD

**Issue by Martmists-GH** [matjojo/desire-paths#27]

**Comment by matjojo** [comment]
I've started work on an update today, I think it may be done around the end of the week but don't quote me on that hehe.

**Comment by matjojo** [comment]
Updated today, Making release post now.

**Comment by Martmists-GH** [comment]
1.15 version crash on servers: https://s.yoosk.pl/OY0g6

Likely due to outdated Fabric API version

**Comment by matjojo** [comment]
Hey, thanks for your report!

Your log has shown me one issue (non crash related) that I've solved (thanks for that) but I don't think this issue is on my side.
The log appears to say that there are two to three different fabric versions in your install. Desire paths does not attach it's own fabric api copy in the jar file.
The api version desire paths runs on is one from 6 days ago and is fully compatible with the newest version. I'll be looking at this with other fabric devs to see if they know why it's going wrong.

If you want to you can help me by sending a list of the mods you are using (screenshot of the mods folder is okay but in text would be better). That way I can test with and without my mod and several others to see what the issue really is.

**Comment by matjojo** [comment]
Nope, what I said above was not the issue. Turns out I was doing some client stuff on the server side, and that crashes the server. 

Next time when you post a log please give some more information, like for example that this is a server log and that the client didn't crash, or if it did, etc etc. New build should be up relatively soon on curse.
